version: '3'

services:
  postgres:
    image: 'postgres:alpine'
    ports:
      - '5432:5432'
    volumes:
      - 'postgresql_data:/var/lib/postgresql'
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    networks:
      - app-net
      - pgadmin

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - '16543:80'
    depends_on:
      - postgres
    networks:
      - pgadmin
    volumes:
      - pgadmin-data:/var/lib/pgadmin

  zookeeper:
    image: 'bitnami/zookeeper:3'
    ports:
      - '2181:2181'
      - '8080:8080'
    volumes:
      - 'zookeeper_data:/bitnami'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - app-net
    depends_on:
      - postgres

  kafka:
    image: 'bitnami/kafka:3'
    ports:
      - '9092:9092'
    volumes:
      - 'kafka_data:/bitnami'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - postgres
      - zookeeper
    networks:
      - app-net

networks:
  pgadmin:
  app-net:
    driver: bridge

volumes:
  pgadmin-data:
    driver: local
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
  postgresql_data:
    driver: local
