version: '3.6'

services:
  mongodb:
    image: bitnami/mongodb:5.0
    ports:
      - '27017:27017'
    volumes:
      - 'mongodb_data:/bitnami/mongodb'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

volumes:
  mongodb_data:
    driver: local
